version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  geth:
    image: ethereum/client-go:${GETH_DOCKER_TAG}
    restart: always
    command: --goerli --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts="*" --allow-insecure-unlock --http.api="db,eth,net,web3,personal"
    ports:
      - 30305:30303/tcp
      - 30305:30303/udp
    volumes:
      - ./data/geth:/root/.ethereum
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    <<: *logging

  beacon:
    image: sigp/lighthouse:${LIGHTHOUSE_DOCKER_TAG}
    volumes:
      - ./data/sigmaprime/lighthouse:/root/.lighthouse
      - ./config/lighthouse/start-beacon-node.sh:/root/scripts/start-beacon-node.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
    env_file: ./config/lighthouse/.env
    command: sh /root/scripts/start-beacon-node.sh
    restart: on-failure
    <<: *logging

  validator:
    image: sigp/lighthouse:${LIGHTHOUSE_DOCKER_TAG}
    volumes:
      - ./config/lighthouse/validator/start-validator-client.sh:/root/scripts/start-validator-client.sh:ro
      - ./wallets:/root/.lighthouse
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - beacon
    env_file: ./config/lighthouse/validator/.env
    command: sh /root/scripts/start-validator-client.sh
    restart: on-failure
    <<: *logging

  prometheus:
    image: prom/prometheus:v2.21.0
    user: root # https://github.com/prometheus/prometheus/issues/5976
    restart: on-failure
    hostname: prometheus
    command: --storage.tsdb.retention.time=7d --config.file=/etc/prometheus/prometheus.yml
    ports:
    - 127.0.0.1:9092:9090
    volumes:
    - ./config/prometheus/prometheus-lh.yaml:/etc/prometheus/prometheus.yml:ro
    - ./data/prometheus:/prometheus
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    <<: *logging

  grafana:
    image: grafana/grafana:7.2.1
    restart: on-failure
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3002:3000
    volumes:
      - ./config/grafana/provisioning-lh:/etc/grafana/provisioning:ro
      - ./data/grafana:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    <<: *logging

# EOF
